[package]
name = "pusoy"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
axum = { version = "0.6", features = ["ws", "macros", "headers"] } 
axum-core = "0.3"
axum-extra = { version = "0.7", features = ["cookie"] }
axum-server = { version = "0.5", features = ["tls-rustls"] }
base64 = "0.21"
bytes = "1"
futures = "0.3"
futures-util = "0.3"
headers = "0.3"
http = "0.2"
http-body = "0.4"
hyper = { version = "0.14", features = ["full"] }
mime = "0.3"
pin-project = "1"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
serde_with = "3.1"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
tower = "0.4"
tower-http = { version = "0.4", features = ["full"] }
uuid = { version = "1", features = ["serde"] }
