[package]
name = "pusoy"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6", features = ["ws", "macros"] } 
axum-extra = { version = "0.7", features = ["cookie"] }
axum-server = { version = "0.5", features = ["tls-rustls"] }
futures = "0.3"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "3.1"
tokio = { version = "1.31", features = ["full"] }
tokio-stream = "0.1"
tower = "0.4"
tower-http = { version = "0.4", features = ["full"] }
uuid = { version = "1.4", features = ["serde"] }
